# Generated by Django 2.2.6 on 2019-10-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.ShoeColor'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Manufacturer'),
        ),
    ]
